---
# check apache2 status on Ubuntu
- name: check apache2 service status in case we running on Ubuntu
  shell: service apache2 status
  register: apache_status
  ignore_errors: True   
  args: 
    warn: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 

# install apache2 on ubuntu
- name: install apache2 on ubuntu in case the service not installed
  apt: name=apache2 state=latest
  notify: start apache service on Ubuntu
  when: apache_status.failed is defined and apache_status.failed == true and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')