---
#
# The following playbook attempt to install 
# apache2 on Ubuntu or httpd on Centos
#
- hosts: host0
  become: true  

  tasks:

##
# following tasks going to install apache2 on Ubuntu
##
  - name: check apache2 service status in case we running on Ubuntu
    shell: service apache2 status
    register: apache_status
    ignore_errors: True   
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 

  - name: install apache2 on ubuntu in case the service not installed
    apt: name=apache2 state=latest
    register: apache_install
    when: apache_status.failed is defined and apache_status.failed == true and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')  

  - name: start apache2 service on Ubuntu
    service: name=apache2 state=restarted
    when: apache_install.skipped is defined and apache_install.skipped == false and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )  

##
# following tasks going to install httpd on Centos
##
  - name: check httpd service status in case we running on Centos  
    shell: service httpd status
    register: httpd_status
    ignore_errors: True
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: install httpd on CentOS in case the service not installed
    yum: name=httpd state=latest
    register: httpd_install
    when: httpd_status.failed is defined and httpd_status.failed == true and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

  - name: start httpd service on Centos
    service: name=httpd state=restarted
    when: httpd_install.skipped is defined and httpd_install.skipped == false and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')