---
- hosts: host0
  become: true  

  tasks:
             
  - debug: 
      var: ansible_default_ipv4.address

  - debug:
      msg: " {{ ansible_default_ipv4.address }} " 

  - name: check status of apache
    #command: service apache2 status
    shell: service apache2 status
    #service: name=docker state=restarted
    register: apache_status
    ignore_errors: True   
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
    #when: ansible_distribution == 'Centos' 
  
  #- debug: var=apache_stat.failed
  
  - name: uninstall apache2
    apt: name=apache2 state=absent
    when: (apache_status.failed is defined) and (apache_status.failed == false) and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )

  - name: install apache2 on Ubuntu
    #debug: var=apache_stat.skipped
    #debug: var=apache_stat.failed
    apt: name=apache2 state=latest
    register: apache_install
    when: (apache_status.failed is defined) and (apache_status.failed == true) and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )

  - debug: var=apache_install
  - name: start apache2 
    service: name=apache2 state=restarted
    #register: apache_start
    #ignore_errors: True 
    when: apache_install.skipped is defined and apache_install.skipped == false and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') 

  - template: src=index.html dest=/etc/index.html