---

- hosts: host2
  become: true

  tasks:
   - name: remove nginx 
     apt: name=nginx state=absent purge=yes autoremove=yes
   - name: remove nginx-common
     apt: name=nginx-common state=absent purge=yes autoremove=yes
